version: "2"
services:
    ReactServer:
        container_name: ReportServer
        image: james/report-server
        build: ./ReportServer
        ports:
            - 8081:3000
        volumes:
            # 對外:對內
          - ~/projects/vita/react-starter-kit/build:/usr/src/app

    PDFServer:
        container_name: PDFServer
        image: james/pdf-server
        build: ./pdfServer
        ports:
            # 對外:對內
          - 8084:3000
        volumes:
            # 對外:對內
          - ~/projects/vita/practice/app:/www/app

# docker-compose up
# docker-compose up -d
# docker-compose ps
# docker-compose stop
